export const IPC = {
  PYTHON_STATUS: 'python:status',
  GET_PYTHON_STATUS: 'python:getStatus',
  PING: 'ping',

  DB_STATUS: 'db:status',
  DB_CLEAR_ALL: 'db:clearAll',

  TASK_CREATE: 'task:create',
  TASK_GET: 'task:get',
  TASK_CANCEL: 'task:cancel',
  TASK_PROGRESS: 'task:progress',
  TASK_PARTIAL: 'task:partial',

  APP_GET_SETTINGS: 'app:getSettings',
  APP_SET_SETTING: 'app:setSetting',
  APP_GET_STORAGE_PATHS: 'app:getStoragePaths',
  APP_SET_STORAGE_PATHS: 'app:setStoragePaths',
  APP_PICK_DIRECTORY: 'app:pickDirectory',
  APP_PICK_IMAGE_FILE: 'app:pickImageFile',
  APP_RELAUNCH: 'app:relaunch',

  QUESTION_QUERY: 'question:query',
  QUESTION_SEARCH: 'question:search',
  QUESTION_GROUP_LIST: 'questionGroup:list',
  QUESTION_GROUP_UPSERT: 'questionGroup:upsert',
  QUESTION_GROUP_DELETE: 'questionGroup:delete',
  QUESTION_GROUP_COUNT: 'questionGroup:count',
  QUESTION_GROUP_MOVE_QUESTIONS: 'questionGroup:moveQuestions',
  QUESTION_GROUP_SYNC_EXAM_META: 'questionGroup:syncExamMeta',
  QUESTION_INSERT: 'question:insert',
  QUESTION_BATCH_INSERT: 'question:batchInsert',
  QUESTION_UPDATE: 'question:update',
  QUESTION_DELETE: 'question:delete',
  QUESTION_BATCH_DELETE: 'question:batchDelete',
  QUESTION_TOGGLE_FAVORITE: 'question:toggleFavorite',
  QUESTION_GET_STATS: 'question:getStats',
  QUESTION_LIST_TAGS: 'question:listTags',
  QUESTION_UPLOAD_IMAGE: 'question:uploadImage',
  QUESTION_DELETE_IMAGE: 'question:deleteImage',
  QUESTION_LIST_IMAGES: 'question:listImages',

  PRACTICE_START: 'practice:start',
  PRACTICE_SUBMIT_ANSWER: 'practice:submitAnswer',
  PRACTICE_END: 'practice:end',
  PRACTICE_GET_WRONG: 'practice:getWrong',

  DOC_LIST: 'doc:list',
  DOC_PICK_FILE: 'doc:pickFile',
  DOC_IMPORT: 'doc:import',
  DOC_PREVIEW: 'doc:preview',
  DOC_DELETE: 'doc:delete',
  DOC_GET_CHUNKS: 'doc:getChunks',
  DOC_SEARCH_CHUNKS: 'doc:searchChunks',
  DOC_UPDATE_CHUNK: 'doc:updateChunk',
  DOC_REPARSE_PAGE: 'doc:reparsePage',
  DOC_GET_ASSETS: 'doc:getAssets',
  DOC_SET_OFFICIAL: 'doc:setOfficial',
  DOC_CLEAN_CHUNKS: 'doc:cleanChunks',
  DOC_UPDATE_CHUNK_TAGS: 'doc:updateChunkTags',
  DOC_GET_CLEANING_LOGS: 'doc:getCleaningLogs',
  DOC_ROLLBACK_CLEANING: 'doc:rollbackCleaning',

  AI_GENERATE_QUESTIONS: 'ai:generateQuestions',
  AI_GRADE_ESSAY: 'ai:gradeEssay',
  AI_TEST_CONNECTION: 'ai:testConnection',
  AI_GET_CONFIG: 'ai:getConfig',
  AI_SET_CONFIG: 'ai:setConfig',

  CRAWLER_LIST_RULES: 'crawler:listRules',
  CRAWLER_UPSERT_RULE: 'crawler:upsertRule',
  CRAWLER_DELETE_RULE: 'crawler:deleteRule',
  CRAWLER_TEST: 'crawler:test',
  CRAWLER_RUN: 'crawler:run',
  CRAWLER_LIST_RUNS: 'crawler:listRuns',
  CRAWLER_DELETE_RUN: 'crawler:deleteRun',
  CRAWLER_UPDATE_RUN: 'crawler:updateRun',
  CRAWLER_LIST_REVIEW_ITEMS: 'crawler:listReviewItems',
  CRAWLER_REJECT_REVIEW_ITEMS: 'crawler:rejectReviewItems',
  CRAWLER_IMPORT_REVIEW_ITEMS: 'crawler:importReviewItems',
  CRAWLER_AUTH_START: 'crawler:authStart',
  CRAWLER_VISUAL_CONFIG: 'crawler:visualConfig',
  CRAWLER_LIST_SESSIONS: 'crawler:listSessions',
  CRAWLER_VALIDATE_SESSION: 'crawler:validateSession',
  CRAWLER_DELETE_SESSION: 'crawler:deleteSession',
  CRAWLER_INSPECT_LOAD: 'crawler:inspectLoad',
  CRAWLER_INSPECT_PREVIEW: 'crawler:inspectPreview',
  CRAWLER_SUGGEST_SELECTOR: 'crawler:suggestSelector',
  CRAWLER_RUNTIME_STATUS: 'crawler:runtimeStatus',

  GRAPH_BUILD: 'graph:build',

  ESSAY_LIST: 'essay:list',
  ESSAY_CREATE: 'essay:create',
  ESSAY_GET: 'essay:get',
  ESSAY_UPDATE_SECTION: 'essay:updateSection',
  ESSAY_UPDATE_META: 'essay:updateMeta',
  ESSAY_SAVE_VERSION: 'essay:saveVersion',
  ESSAY_LIST_VERSIONS: 'essay:listVersions',
  ESSAY_RESTORE_VERSION: 'essay:restoreVersion',
  ESSAY_DELETE: 'essay:delete',
  ESSAY_LIST_MATERIALS: 'essay:listMaterials',
  ESSAY_UPSERT_MATERIAL: 'essay:upsertMaterial',
  ESSAY_DELETE_MATERIAL: 'essay:deleteMaterial',
  ESSAY_AI_SUGGEST: 'essay:aiSuggest',

  AI_CHAT: 'ai:chat',
  AI_CHAT_SESSIONS_LIST: 'ai:chatSessions:list',
  AI_CHAT_SESSION_CREATE: 'ai:chatSession:create',
  AI_CHAT_SESSION_DELETE: 'ai:chatSession:delete',
  AI_CHAT_MESSAGES_LIST: 'ai:chatMessages:list',

  PLAN_GET_ACTIVE: 'plan:getActive',
  PLAN_CREATE: 'plan:create',
  PLAN_DELETE: 'plan:delete',
  PLAN_GET_TASKS: 'plan:getTasks',
  PLAN_UPDATE_TASK: 'plan:updateTask',
  PLAN_GET_STATS: 'plan:getStats',
  PLAN_GET_CALENDAR: 'plan:getCalendar',
  PLAN_ADAPT: 'plan:adapt',

  SESSION_START: 'session:start',
  SESSION_END: 'session:end',
  SESSION_GET_TODAY: 'session:getToday',

  ACHIEVEMENT_LIST: 'achievement:list',
  ACHIEVEMENT_CHECK: 'achievement:check',

  BACKUP_CREATE: 'backup:create',
  BACKUP_LIST: 'backup:list',
  BACKUP_RESTORE: 'backup:restore',
  BACKUP_DELETE: 'backup:delete',

  IMAGE_CLEANUP_ORPHANS: 'image:cleanupOrphans',
  IMAGE_ENSURE_LOCAL: 'image:ensureLocal',

  QUESTION_EXPORT: 'question:export',
  QUESTION_IMPORT_FILE: 'question:importFile',
  QUESTION_APPLY_AUTO_TAGS: 'question:applyAutoTags',
  QUESTION_GET_TAG_HISTORY: 'question:getTagHistory',

  // ─── Study Plan Overhaul — Exam Config ─────────────────────────────────────
  EXAM_CONFIG_GET: 'examConfig:get',
  EXAM_CONFIG_SAVE: 'examConfig:save',

  // ─── Study Plan Overhaul — Knowledge Domains ───────────────────────────────
  KD_TREE: 'kd:tree',
  KD_GET: 'kd:get',
  KD_UPSERT: 'kd:upsert',
  KD_DELETE: 'kd:delete',
  KD_IMPORT_OUTLINE: 'kd:importOutline',
  KD_MAP_DOC: 'kd:mapDoc',
  KD_FLAT_LIST: 'kd:flatList',
  KD_BATCH_UPSERT: 'kd:batchUpsert',
  KD_GET_CHUNKS_FOR_DOCS: 'kd:getChunksForDocs',
  AI_EXTRACT_KNOWLEDGE: 'ai:extractKnowledge',
  AI_EXTRACT_PROGRESS: 'ai:extractKnowledge:progress',
  AI_RECLASSIFY_CHUNK: 'ai:reclassifyChunk',
  AI_RECLASSIFY_CHUNK_BATCH: 'ai:reclassifyChunkBatch',
  AI_AUTO_TAG_QUESTIONS: 'ai:autoTagQuestions',
  AI_CLASSIFY_QUESTION_TAGS: 'ai:classifyQuestionTags',

  // ─── Study Plan Overhaul — Learning Logs ───────────────────────────────────
  LOG_CREATE: 'log:create',
  LOG_QUERY: 'log:query',
  LOG_STATS: 'log:stats',
  LOG_UPDATE: 'log:update',
  LOG_DELETE: 'log:delete',

  // ─── Study Plan Overhaul — Enhanced Plan Operations ────────────────────────
  PLAN_GENERATE_PHASED: 'plan:generatePhased',
  PLAN_LOCK_DAYS: 'plan:lockDays',
  PLAN_UNLOCK_DAYS: 'plan:unlockDays',
  PLAN_RESET: 'plan:reset',
  PLAN_ADD_CUSTOM_TASK: 'plan:addCustomTask',
  PLAN_MOVE_TASK: 'plan:moveTask',
  PLAN_SKIP_DAY: 'plan:skipDay',
  PLAN_RELINK_DOCS: 'plan:relinkDocs',
  PLAN_REMAP_CHUNK_TAGS: 'plan:remapChunkTags',
  PLAN_APPLY_AI_SCHEDULE: 'plan:applyAiSchedule',

  // ─── Study Plan Overhaul — Plan Templates ──────────────────────────────────
  TEMPLATE_LIST: 'template:list',
  TEMPLATE_CREATE: 'template:create',
  TEMPLATE_DELETE: 'template:delete',
  TEMPLATE_APPLY: 'template:apply',

  // ─── Study Plan Overhaul — Sprint Mode ─────────────────────────────────────
  SPRINT_STATUS: 'sprint:status',
  SPRINT_ACTIVATE: 'sprint:activate',
  SPRINT_DAILY_CARD: 'sprint:dailyCard',

  // ─── Study Plan Overhaul — Notifications ───────────────────────────────────
  NOTIFICATION_LIST: 'notification:list',
  NOTIFICATION_MARK_READ: 'notification:markRead',
  NOTIFICATION_CHECK_TRIGGERS: 'notification:checkTriggers',

  // ─── Study Plan Overhaul — Pomodoro Enhanced ───────────────────────────────
  SESSION_START_POMODORO: 'session:startPomodoro',
  SESSION_REPORT_INTERRUPTION: 'session:reportInterruption',
  SESSION_GET_FOCUS_STATS: 'session:getFocusStats',

  // ─── Study Plan Overhaul — AI Integration ──────────────────────────────────
  AI_PLAN_ADVICE: 'ai:planAdvice',
  AI_GENERATE_PLAN_TEMPLATE: 'ai:generatePlanTemplate',
  AI_GENERATE_STUDY_PLAN: 'ai:generateStudyPlan',
  AI_OPTIMIZE_PLAN: 'ai:optimizePlan',
  AI_ESSAY_MATERIAL_MATCH: 'ai:essayMaterialMatch',
  AI_DAILY_RECOMMENDATION: 'ai:dailyRecommendation',
} as const
