export const IPC = {
  PYTHON_STATUS: 'python:status',
  GET_PYTHON_STATUS: 'python:getStatus',
  PING: 'ping',

  DB_STATUS: 'db:status',

  TASK_CREATE: 'task:create',
  TASK_GET: 'task:get',
  TASK_CANCEL: 'task:cancel',
  TASK_PROGRESS: 'task:progress',

  APP_GET_SETTINGS: 'app:getSettings',
  APP_SET_SETTING: 'app:setSetting',
  APP_GET_STORAGE_PATHS: 'app:getStoragePaths',
  APP_SET_STORAGE_PATHS: 'app:setStoragePaths',
  APP_PICK_DIRECTORY: 'app:pickDirectory',
  APP_RELAUNCH: 'app:relaunch',

  QUESTION_QUERY: 'question:query',
  QUESTION_SEARCH: 'question:search',
  QUESTION_GROUP_LIST: 'questionGroup:list',
  QUESTION_GROUP_UPSERT: 'questionGroup:upsert',
  QUESTION_GROUP_DELETE: 'questionGroup:delete',
  QUESTION_INSERT: 'question:insert',
  QUESTION_BATCH_INSERT: 'question:batchInsert',
  QUESTION_UPDATE: 'question:update',
  QUESTION_DELETE: 'question:delete',
  QUESTION_TOGGLE_FAVORITE: 'question:toggleFavorite',
  QUESTION_GET_STATS: 'question:getStats',

  PRACTICE_START: 'practice:start',
  PRACTICE_SUBMIT_ANSWER: 'practice:submitAnswer',
  PRACTICE_END: 'practice:end',
  PRACTICE_GET_WRONG: 'practice:getWrong',

  DOC_LIST: 'doc:list',
  DOC_PICK_FILE: 'doc:pickFile',
  DOC_IMPORT: 'doc:import',
  DOC_PREVIEW: 'doc:preview',
  DOC_DELETE: 'doc:delete',
  DOC_GET_CHUNKS: 'doc:getChunks',

  AI_GENERATE_QUESTIONS: 'ai:generateQuestions',
  AI_GRADE_ESSAY: 'ai:gradeEssay',
  AI_TEST_CONNECTION: 'ai:testConnection',
  AI_GET_CONFIG: 'ai:getConfig',
  AI_SET_CONFIG: 'ai:setConfig',

  CRAWLER_LIST_RULES: 'crawler:listRules',
  CRAWLER_UPSERT_RULE: 'crawler:upsertRule',
  CRAWLER_DELETE_RULE: 'crawler:deleteRule',
  CRAWLER_TEST: 'crawler:test',
  CRAWLER_RUN: 'crawler:run',
  CRAWLER_LIST_RUNS: 'crawler:listRuns',
  CRAWLER_LIST_REVIEW_ITEMS: 'crawler:listReviewItems',
  CRAWLER_REJECT_REVIEW_ITEMS: 'crawler:rejectReviewItems',
  CRAWLER_IMPORT_REVIEW_ITEMS: 'crawler:importReviewItems',
  CRAWLER_AUTH_START: 'crawler:authStart',
  CRAWLER_LIST_SESSIONS: 'crawler:listSessions',
  CRAWLER_VALIDATE_SESSION: 'crawler:validateSession',
  CRAWLER_DELETE_SESSION: 'crawler:deleteSession',
  CRAWLER_INSPECT_LOAD: 'crawler:inspectLoad',
  CRAWLER_INSPECT_PREVIEW: 'crawler:inspectPreview',
  CRAWLER_SUGGEST_SELECTOR: 'crawler:suggestSelector',

  GRAPH_BUILD: 'graph:build',

  ESSAY_LIST: 'essay:list',
  ESSAY_CREATE: 'essay:create',
  ESSAY_GET: 'essay:get',
  ESSAY_UPDATE_SECTION: 'essay:updateSection',
  ESSAY_UPDATE_META: 'essay:updateMeta',
  ESSAY_SAVE_VERSION: 'essay:saveVersion',
  ESSAY_LIST_VERSIONS: 'essay:listVersions',
  ESSAY_RESTORE_VERSION: 'essay:restoreVersion',
  ESSAY_DELETE: 'essay:delete',
  ESSAY_LIST_MATERIALS: 'essay:listMaterials',
  ESSAY_UPSERT_MATERIAL: 'essay:upsertMaterial',
  ESSAY_DELETE_MATERIAL: 'essay:deleteMaterial',
  ESSAY_AI_SUGGEST: 'essay:aiSuggest',

  AI_CHAT: 'ai:chat',
  AI_CHAT_SESSIONS_LIST: 'ai:chatSessions:list',
  AI_CHAT_SESSION_CREATE: 'ai:chatSession:create',
  AI_CHAT_SESSION_DELETE: 'ai:chatSession:delete',
  AI_CHAT_MESSAGES_LIST: 'ai:chatMessages:list',

  PLAN_GET_ACTIVE: 'plan:getActive',
  PLAN_CREATE: 'plan:create',
  PLAN_DELETE: 'plan:delete',
  PLAN_GET_TASKS: 'plan:getTasks',
  PLAN_UPDATE_TASK: 'plan:updateTask',
  PLAN_GET_STATS: 'plan:getStats',
  PLAN_GET_CALENDAR: 'plan:getCalendar',
  PLAN_ADAPT: 'plan:adapt',

  SESSION_START: 'session:start',
  SESSION_END: 'session:end',
  SESSION_GET_TODAY: 'session:getToday',

  ACHIEVEMENT_LIST: 'achievement:list',
  ACHIEVEMENT_CHECK: 'achievement:check',

  BACKUP_CREATE: 'backup:create',
  BACKUP_LIST: 'backup:list',
  BACKUP_RESTORE: 'backup:restore',
  BACKUP_DELETE: 'backup:delete',
} as const
